apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      imagePullSecrets:
        - name: docker.bedson.tech
      containers:
      - name: analytics
        image: docker.bedson.tech/tbedson/analytics:0.1.0
        env:
          - name: GIN_MODE
            value: release
          - name: DB_HOST
            value: analytics-pg-service
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: analytics-pg-secret
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: analytics-pg-secret
                key: POSTGRES_PASSWORD
          - name: DB_DATABASE
            value: analytics
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  type: NodePort
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-pg
spec:
  selector:
    matchLabels:
      app: analytics-pg
  template:
    metadata:
      labels:
        app: analytics-pg
    spec:
      containers:
      - name: analytics-pg
        image: postgres:18-alpine
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: analytics-pg-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: analytics-pg-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            value: analytics
        ports:
            - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: analytics-pg-data
      volumes:
        - name: analytics-pg-data
          persistentVolumeClaim:
            claimName: analytics-pg-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-pg-pvc
  labels:
    app: analytics-pg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-pg-service
  labels:
    app: analytics-pg
spec:
  selector:
    app: analytics-pg
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-pg-secret
  labels:
    app: analytics-pg
type: Opaque
data:
  POSTGRES_USER: ZGVmYXVsdA==
  POSTGRES_PASSWORD: ZGVmYXVsdA==